uploads = []
generated = []

[[outputs]]
id = "Oja8uG5Y5Jr1tuctC_x8E"
uri = "file://artifacts/football-dashboard/live/data/tm_scrap/sfa1.csv"
type = "table"
title = "SFA1 (Betway Premiership) — Stats joueurs 5 saisons"
